backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: 'assets/uploads'
public_folder: '/uploads'

collections:
  - name: 'project'
    label: 'Project'
    folder: 'assets/content/projects'
    create: true
    format: 'json'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          default: ['Front-end Development'],
        }
      - { label: 'Description', name: 'description', widget: 'string' }
      - label: 'Featured Image (on card)'
        name: 'feature_image'
        widget: 'image'
      - label: 'Banner Images'
        name: 'banner_images'
        widget: 'list'
        field: { label: Image, name: image, widget: image }
      - label: 'Content'
        name: 'sections'
        widget: 'list'
        types:
          - label: 'Content'
            name: 'content'
            widget: object
            fields:
              - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Image'
            name: 'image'
            widget: object
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - {
                  label: 'Caption',
                  name: 'caption',
                  widget: 'string',
                  required: false,
                }
          - label: 'Dual Images'
            name: 'dual_images'
            widget: object
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - {
                  label: 'Caption',
                  name: 'caption',
                  widget: 'string',
                  required: false,
                }
              - { label: 'Image 2', name: 'image_2', widget: 'image' }
              - {
                  label: 'Caption 2',
                  name: 'caption_2',
                  widget: 'string',
                  required: false,
                }
          - label: 'Title and Pre'
            name: 'title_with_pre'
            widget: object
            fields:
              - {
                  label: 'Pre-title',
                  name: 'pre_title',
                  widget: 'string',
                  default: 'Feature',
                }
              - { label: 'Title', name: 'title', widget: 'string' }
